server:
  port: 80
  ​
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/ # 入驻地址

ribbon:
  #建立连接所用时间  两端连接所用时间
  ReadTimeout: 5000
  # 建立连接后从服务器读取可用资源的所用时间
  ConnectTimeout: 5000

logging:
  level:
    # feign 日志以什么级别监控哪个接口
    com.atguigu.springcloud.service.PaymentFeignService: debug
